# Site settings
author: Shahwar
title: Explore Top Companies' opportunity
header-img: img/home-bg.png
email: shevy.spall@gmail.com
copyright_name: Shahwar
description: > # this means to ignore newlines until "baseurl:"
  This is design to explore about the hiring company's background.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  shahwarspall

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
